apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: fashion-mnist-classifier
  namespace: default
spec:
  annotations:
    seldon.io/rest-timeout: "60"
    seldon.io/grpc-timeout: "60"
  protocol: seldon
  predictors:
  - componentSpecs:
    - spec:
        containers:
        - image: vadyusikh/app-seldon:latest
          name: classifier
          env:
          - name: GUNICORN_THREADS
            value: '1'
          - name: GUNICORN_WORKERS
            value: '1'
          - name: FLASK_SINGLE_THREADED
            value: '1'
          - name: SELDON_DEBUG
            value: '1'          
          - name: WANDB_API_KEY
            value: 62cfffbb52717ad595b33f3e24b2673e36b3cf90
          imagePullPolicy: Always

    graph:
      name: fashion-mnist-classifier
      type: MODEL
      # parameters: [
      #   {
      #     "name": "model_load_path",
      #     "type": "STRING",
      #     "value": "model-artifacts/"
      #   }
      # ]
    name: model
    replicas: 1
