name: week-2-ci

on:
  push:
    branches:
      - 'main'
      - 'week2-minio'

jobs:
  minio-deploy:
    runs-on: ubuntu-latest
    name: build example and deploy to minikube
    steps:
    - uses: actions/checkout@v2
    - name: Start minikube
      uses: medyagh/setup-minikube@master

    - name: Try the cluster !
      run: minikube kubectl get pods

    - name: Deploy minio to minikube
      run: |
        kubectl create -f week2/minio/minio-standalone.yaml
        kubectl wait --for=condition=complete --timeout=300s pod/minio-deployment
        kubectl get pods