# This is a basic workflow to help you get started with Actions

name: week3-CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "week3", "week3-part2-test-code", "week3-part2-test-model", "week3-part2-test-data" ]
  pull_request:
    branches: [ "week3", "week3-part2-test-code", "week3-part2-test-model", "week3-part2-test-data" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  DOCKER_IMAGE_NAME: ml_in_prod
  DOCKER_IMAGE_VERSION : week3_latest
  DOCKER_IMAGE_FULL_NAME : ml_in_prod:week3_latest
  DOCKER_IMAGE_HUB_PATH : ${{ secrets.DOCKER_HUB_USERNAME }}/ml_in_prod:week3_latest

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build docker
        uses: docker/build-push-action@v2
        with:
          context: week3/image_classification
          file: week3/image_classification/Dockerfile
          push: false
          tags: ${{ secrets.DOCKER_IMAGE_HUB_PATH }}
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:buildcache,mode=max
      -
        name: Pull docker
        run: docker pull ${{ secrets.DOCKER_IMAGE_HUB_PATH }}
      -
        name: Go to makefile
        run: |
          cd week3/image_classification
          ls
      -
        name: Build new
        run: |
          make build
      -
        name: Test code
        run: |
          docker run ${{ env.DOCKER_IMAGE_FULL_NAME }} make test_code
      -
        name: Test data
        run: |
          docker run ${{ env.DOCKER_IMAGE_FULL_NAME }} make test_data
      -
        name: Test model
        run: |
          docker run ${{ env.DOCKER_IMAGE_FULL_NAME }} make test_model
      -
        name: Test all
        run: |
          docker run ${{ env.DOCKER_IMAGE_FULL_NAME }} make test_all
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: week3/image_classification
          file: week3/image_classification/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_IMAGE_HUB_PATH }}
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:buildcache,mode=max
